# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://thirdactivedataextech.github.io/
title: ThirdActiveDataExTech
email: irisdev@mobigen.com
author: Eunmi Go
description: > # "Write an awesome description for your new site here.
  써드파티데이터의 활용성 증대를 위한 액티브 메타데이터 기반 능동형 데이터 확장 기술 개발
copyright: 'Copyright &copy; 2024- ThirdActiveDataExTech Project. All Rights Reserved.'
credits: 'This project is supported by <a href="https://www.mobigen.com">IITP</a> grant funded by the Korea government(MSIT) (No.,)'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
#permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/ThirdActiveDataExTech
  - title: documentation (eng)
    url: https://github.com/ThirdActiveDataExTech
  - title: documentation (kor)
    url: https://github.com/ThirdActiveDataExTech